---
title: "Exercise 05"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r global}
library(tidyverse)
library(flexdashboard)
ggplot2::theme_set(ggplot2::theme_bw())

d = readr::read_csv(here::here("data/weather.csv"))
```

```{r}
d_vars = d |>
  select(where(is.numeric)) |>
  names()

d_city = reactive({
  d |>
    filter(city %in% input$city)
})
```

Col {data-width=800}
-------------------------------------

###

```{r}
selectInput(
  "city", "Select a city",
  choices = c("Chicago", "Durham", "Sedona", "New York", "Los Angeles")
)
selectInput(
  "var", "Select a variable",
  choices = d_vars, selected = "temp"
)

renderPlot({
  d_city() |>
    ggplot(aes(x=time, y=.data[[input$var]])) +
    ggtitle(input$var) +
    geom_line()
}, height=500)
```

Col {data-width=200}
-------------------------------------

### Min `r renderText(input$var)`

```{r}
renderValueBox({
  valueBox(
    min(d_city()[[input$var]]) |> round(2),
    caption = paste("Min", input$var),
    color = "primary"
  )
})
```

### Avg `r renderText(input$var)`

```{r}
renderGauge({
  gauge(
    mean(d_city()[[input$var]]) |> round(2),
    min = min(d_city()[[input$var]]), 
    max = max(d_city()[[input$var]])
  )
})

#renderValueBox({
#  valueBox(
#    ,
#    caption = paste("Avg", input$var),
#    color = "success"
#  )
#})
```

### Max `r renderText(input$var)`

```{r}
renderValueBox({
  valueBox(
    max(d_city()[[input$var]]) |> round(2),
    caption = paste("Max", input$var),
    color = "danger"
  )
})
```


