---
title: "Demo 04"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r global}
library(tidyverse)

d = readr::read_csv(here::here("data/weather.csv"))
```

```{r}
d_vars = d |>
  select(where(is.numeric)) |>
  names()

d_city = reactive({
  d |>
    filter(city %in% input$city)
})
```


Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  "city", "Select a city",
  choices = c("Chicago", "Durham", "Sedona", "New York", "Los Angeles")
)

selectInput(
  "var", "Select a variable",
  choices = d_vars, selected = "humidity"
)
```


Row {data-height=650}
-------------------------------------

### Temperature

```{r}
renderPlot({
  d_city() |>
    ggplot(aes(x=time, y=temp)) +
    ggtitle(input$city) + 
    geom_line()
})
```

Row {data-height=350}
-------------------------------------
   
### Other

```{r}
renderPlot({
  d_city() |>
    ggplot(aes(x=time, y=.data[[input$var]])) +
    geom_line()
})
```   

### Temperature Summary

```{r}
renderTable({
  d_city() |>
    mutate(
      day = lubridate::wday(time, label = TRUE, abbr = FALSE),
      date = as.character(lubridate::date(time))
    ) |>
    group_by(date, day) |>
    summarize(
      `min` = min(temp),
      `max` = max(temp),
      .groups = "drop"
    ) 
})
```
